name: bbichul-frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest # OS환경
    env: # 환경변수
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps: # 파이프라인이 실행되는 순서
      # 1.컨테이너 내에서 소스를 checkout받는다.
      - name: Checkout source code.
        uses: actions/checkout@master

      # 2.파일을 S3로 업로드 시킨다.
      - name: Upload binary to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --exclude '*' --include '*'
        env:
          AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}

      # 3.Cloudfront 캐싱 refrash
      - name: Invalidate cache CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
          PATHS: "/index.html"
        continue-on-error: true